### ISSUE TITLE
Error 500 when editing events or instances

### ISSUE THREAD

**Issue by djpinger** [gotzl/accservermanager#17]
Newly installed, tried both native (git clone, following instructions), or via docker (using example docker-compose.yml from README).  I tried using both a docker volume, and direct volume mapping to local directories.  Docker logs show:

accservermanager | [29/Jun/2020 06:01:53] "GET /cfgs/event HTTP/1.1" 500 1830
accservermanager | [29/Jun/2020 06:02:15] "GET /instances/ HTTP/1.1" 500 1830

**Comment by gotzl** [comment]
Thanks for notifying me about this issue. It seems, that ACC now ships with UTF16 encoded .json files. So, I've to figure out where I need to put `open(.., encoding='utf-16')` or if I can set it globally somehow... I'll report back soon when it's fixed.

**Comment by gotzl** [comment]
My latest release should work again. Note that old configs/instances will not work anymore.
