### ISSUE TITLE
Publish docker image to docker hub

### ISSUE THREAD

**Issue by grimsi** [gotzl/accservermanager#2]
This guide explains how to push a image to docker hub: https://ropenscilabs.github.io/r-docker-tutorial/04-Dockerhub.html

Publishing the image would allow users to simply run the image with something like:
docker run -d --name accserver-manager -v <PATH_TO_ACC>/server:/server -p 8000:8000 -p 9231:9231/udp -p 9232:9232/tcp gotzl/accservermanager

**Comment by gotzl** [comment]
Thanks for your suggestion(s)!

**Comment by gotzl** [comment]
Image is now available from [docker hub](https://hub.docker.com/r/gotzl/accservermanager).

**Comment by grimsi** [comment]
I just found out that you can skip the "docket volume create" because docker will check if a volume with the name exists and will create one if not.
Although this should be used with care because there have been discussions about the deprecation of this feature: https://github.com/moby/moby/issues/16072
