### ISSUE TITLE
ACC game completely stuck when I wan to join server

### ISSUE THREAD

**Issue by Danielvr** [gotzl/accservermanager#21]
Hi I use the newest DockerImage and after the server is running and I want to join the ACC Game completely freeze and I need to force close it.

I don't see strange things in the server log,
[server.log](https://github.com/gotzl/accservermanager/files/5248613/server.log)

**Comment by gotzl** [comment]
I'm pretty sure that this has s.t. todo with traffic not being routed to/from container (9231/udp,9232/tcp). Can you try to run docker with `--net = "host"` (or `network_mode: "host"` in docker-compose.yml)?

**Comment by GlenWright** [comment]
I'm experiencing the same, though I've got a different setup. I have ACC Server Manager deployed on a K8S cluster, sitting behind Traefik. It seems to intermittently fail to register in the server list, normally deleting and recreating an instance will solve this. When connecting to it, the game will freeze. The last two logs in the game log file will be:

LogKsPhysics: Connecting to xx.xx.xxx.xxx : 9232
LogKsPhysics: Error: TCP socket setTimeout error detected 10038

At the Traefik side it looks like a lot of "connection reset by peer".

**Comment by gotzl** [comment]
I believe that this is an issue with the alpine based-docker image. I've changed it to a debian-based image which fixes this issue for me on a machine where it didn't work before.

**Comment by Danielvr** [comment]
I'm going to try it today.

**Comment by Danielvr** [comment]
I've tried and it worked. Thanks 👍

**Comment by gotzl** [comment]
Thank you for confirming!
