### ISSUE TITLE
ACCEXEC list bug

### ISSUE THREAD

**Issue by Kyberal** [gotzl/accservermanager#22]
Hello,

I believe this is a bug.

My environment is Windows Server version 2004 (No GUI) and Python 3.9.0.

I get the following error for "ACCEXEC" variable.

`[10/Nov/2020 17:22:46] "GET /instances/ HTTP/1.1" 200 16342
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\AC\accservermanager\instances\Executor.py", line 45, in run
    exec = os.path.join(self.instanceDir, settings.ACCEXEC)
  File "C:\Program Files\Python39\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Program Files\Python39\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'
[10/Nov/2020 17:23:27] "POST /instances/start HTTP/1.1" 500 1830`

I believe this happens because the default check of "ACCEXEC" to see if the environment is running Wine it outputs a list instead of a string.

The default "ACCEXEC" is:
`ACCEXEC = [i for i in [WINE_PATH, ACC_SERVER_PATH] if i]`

As a quick workaround I changed it to:
`ACCEXEC = ACC_SERVER_PATH`

Everything else is working really good so far.

Thanks for the tool!

**Comment by gotzl** [comment]
Hi, this should be fixed by modifying `accservermanager\instances\Executor.py` line 45 to `...self.instanceDir, *settings.ACCEXEC)` (note the '*'). Can you try this and keep the ACCEXEC in local_settings as is before?

**Comment by Kyberal** [comment]
> Hi, this should be fixed by modifying `accservermanager\instances\Executor.py` line 45 to `...self.instanceDir, *settings.ACCEXEC)` (note the '*'). Can you try this and keep the ACCEXEC in local_settings as is before?

LGTM!
