### ISSUE TITLE
Static files seem to be missing.

### ISSUE THREAD

**Issue by solarisfire** [gotzl/accservermanager#25]
I've got everything running correctly, I've installed all of the requirements:

```
solarisfire@Test-Server:~/accservermanager$ pip3 install -r requirements.txt
Requirement already satisfied: certifi==2019.6.16 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2019.6.16)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: Django==2.2.18 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.2.18)
Requirement already satisfied: django-bootstrap-breadcrumbs==0.9.1 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.9.1)
Requirement already satisfied: django-material==1.5.8 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (1.5.8)
Requirement already satisfied: django-tables2==2.1.0 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (2.1.0)
Requirement already satisfied: idna==2.8 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (2.8)
Requirement already satisfied: nose==1.3.7 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (1.3.7)
Requirement already satisfied: pytz==2019.2 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (2019.2)
Requirement already satisfied: Random-Word==1.0.4 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (1.0.4)
Requirement already satisfied: requests==2.22.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 11)) (2.22.0)
Requirement already satisfied: six==1.12.0 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (1.12.0)
Requirement already satisfied: sqlparse==0.3.0 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (0.3.0)
Requirement already satisfied: urllib3==1.25.3 in /home/solarisfire/.local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (1.25.3)
```

However, when viewing in a browser I get lots of 404s for files in that static directory:
![acc](https://user-images.githubusercontent.com/420952/112765218-0ac6c600-9004-11eb-882f-16aa0243a36e.png)

**Comment by solarisfire** [comment]
Did try running

`python3 manage.py collectstatic`

Which generated a folder called static, but no further luck.

**Comment by gotzl** [comment]
The django devel server only serves static files if it is set to 'debug' mode. You can do this with `DEBUG=true python manage.py runserver`.
The 'right' way to serve the static files would be to use the `collectstatic` command and use nginx or apache to serve the files that appear in the `static` folder.

**Comment by solarisfire** [comment]
Yeah, I did that and it works :-)

Using the Apache config:

`Alias "/static" "/var/www/static"

        <Directory /var/www/static>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Order allow,deny
                Allow from all
        </Directory>

        <Proxy "*">
                Order allow,deny
                Allow from all
        </Proxy>

        ProxyPassMatch ^/static !
        ProxyPass / http://127.0.0.1:8000/
        ProxyPassReverse / http://127.0.0.1:8000/`

With the static files copied to /var/www/satic.

Thanks :-)
