### ISSUE TITLE
eventRules.json

### ISSUE THREAD

**Issue by dusnake** [gotzl/accservermanager#26]
Hello.

First of all, thank you for sharing your work, it is excellent and a pleasure to have people like you in these environments.

I have a question for you, would it be possible to add the assistRules.json somehow?

{
 "stabilityControlLevelMax": 25,
 "disableAutosteer": 1,
 "disableAutoLights": 0,
 "disableAutoWiper": 0,
 "disableAutoEngineStart": 0,
 "disableAutoPitLimiter": 0,
 "disableAutoGear": 0,
 "disableAutoClutch": 0,
 "disableIdealLine": 0
}

**Comment by gotzl** [comment]
I'm happy to see other people interested in this little project  :) I've implemented your suggestion, please try it out and tell me what you think ...

**Comment by dusnake** [comment]
Thank you very much for the speed and for the help, I am very grateful to you.

I have updated my container and the data can already be seen !!

But I have seen two small errors.

In this version, every time I create a "configs", I have to restart the container so that "instances" will recognize it, which did not happen before.

And when launching the instance, the section "Download assistRules" shows other data:

{
    "udpPort": 9231,
    "tcpPort": 9232,
    "maxConnections": 85,
    "lanDiscovery": 0,
    "registerToLobby": 1,
    "configVersion": 1
}

**Comment by gotzl** [comment]
Thanks for the quick feedback, should be better now...

**Comment by dusnake** [comment]
Now it looks great, thank you man !! if I can buy you a beer somehow tell me

**Comment by gotzl** [comment]
:D My pleasure! Feel free to post any further proposals!
Cheers!
