### ISSUE TITLE
Link to https://simresults.net/

### ISSUE THREAD

**Issue by dusnake** [gotzl/accservermanager#28]
Hello again.

This time I am writing to discuss a possible improvement that I think is easy to implement.
The following page:
https://simresults.net/

It is capable of reading the "results" files of various games, including ACC.

It has a utility, which by putting:

https://simresults.net/remote?result=${ourlinkresults}, it shows you the data of the races with a lot of information, for example:

https://simresults.net/remote?result=http://fa4racersacc.duckdns.org/instances/somename2/results/210412_222856_Q.json

The variable ${ourlinkresults} It is the result of the url that your link "Download button" speaks at the end of the race.

Could you add a button that will have that url with the data of our json results?

**Comment by gotzl** [comment]
Hi,

interesting ;) I've just submitted the change, I'm not sure though if it will pick-up the correct domain name. I've no good means to test this right now, so I would appreciate if you could test it out.

**Comment by dusnake** [comment]
Hello mate.

Sorry for the delay, I checked the new functionality today and it works perfect. Thanks a million as always.
