### ISSUE TITLE
copy customcars

### ISSUE THREAD

**Issue by dusnake** [gotzl/accservermanager#39]
Hi there.

I am seeing the option of being able to copy the folder "cars" inside my server to each "instance" that I create.
Inside server \ cfg \ cars you can put "json" to put custom car skins. I would like that folder could be copied from the beginning to each "instance" that is created. Would it be possible?

**Comment by gotzl** [comment]
Can you check if the dir exists? `ls /server/cfg/`

> views.py dont update :(
what do you mean by that?
