### ISSUE TITLE
Use Docker volumes for persistence

### ISSUE THREAD

**Issue by grimsi** [gotzl/accservermanager#5]
As explained [here](https://docs.docker.com/storage/volumes/) Docker volumes are best-practice to persist data generated and used by a container. Using a volume would remove the need to backup the data from the container manually.

**Comment by grimsi** [comment]
I will try to integrate this later and open a new pull request

**Comment by grimsi** [comment]
support for docker volumes added (see #6)

**Comment by gotzl** [comment]
I've merged your suggestion, but changed the scheme slightly (when I tried your solution in linux, I got 'failed to copy xattrs: failed to set xattr "security.selinux"' when docker tried to execute the VOLUME instruction). I also didn't like that the data was floating around inside the project.
The directory where the persistent data is placed is now called DATA_DIR, and it defaults to '/data', which corresponds to the volume created in the dockerfile.
The behavior is same as your suggestion, except that the settings.py is not persisted. But I'm not sure if it is meant to be persisted anyways...

**Comment by grimsi** [comment]
I would extract the parts of the settings.py that should be persisted, like ALLOWED_HOSTS, SECRET_KEY.
It would be tedious if they have to be restored after every update

**Comment by gotzl** [comment]
Yes, true. I'll check tomorrow if there is a canonical solution for this kind of issue in the Django world...

**Comment by gotzl** [comment]
I've decided to go both ways. 
People w/o docker have to edit and take care of accservermanager/local_settings.py.
People with docker don't have to touch (local_)settings.py. They configure the container with env vars, specifically 'SECRET_KEY' and 'ALLOWED_HOSTS'. Experienced users will put these values inside docker-compose.yml... 
What do you think?

**Comment by grimsi** [comment]
I think that's the optimal solution since it allows parameterized automated deployment and management
