### ISSUE TITLE
[Bug] Server instances are not completely deleted

### ISSUE THREAD

**Issue by grimsi** [gotzl/accservermanager#7]
**Summary:**
When a server instance is deleted there are still traces left behind somewhere (I guess in the database?)

**Steps to reproduce:**
1. Create a new instance with name 'test'.
2. Delete instance with name 'test'
3. Create another instance with name 'test'

**Expected result:**
Second instance 'test' gets created since the first one got deleted.

**Actual result:**
Second instance wont be created.

**Additional information:**
Restarting the container does not help.
The folder for the instance gets deleted, so my guess is that the traces have to be in the database.

**Comment by gotzl** [comment]
Closing, should be solved since referenced commit.
