### ISSUE TITLE
"Server Admin Handbook" has been released

### ISSUE THREAD

**Issue by CoryManson** [gotzl/accservermanager#8]
We finally have some documentation for v1.0: https://www.assettocorsa.net/forum/index.php?threads/the-server-admin-handbook-thread.58245/

I'd love to see all the new options and entrylist.json supported in the frontend.

**Comment by grimsi** [comment]
I'm currently busy implementing the ACC 1.0 changes in my own server manager but after that's done I can try to help you out here

**Comment by gotzl** [comment]
In the meantime, the info from the manual is integrated into the app.
